# Generated by Django 4.1.7 on 2023-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_dirtyimage_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirtyimage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
