# Generated by Django 4.1.7 on 2023-07-10 10:24

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_blogtag_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.CharField(default=manager.models.new_uid, max_length=255),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='uid',
            field=models.CharField(default=manager.models.new_uid, max_length=255),
        ),
        migrations.AddField(
            model_name='dirtyimage',
            name='uid',
            field=models.CharField(default=manager.models.new_uid, max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
    ]
