# Generated by Django 4.2.3 on 2023-07-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_blog_tags_alter_blogtag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(null=True, to='manager.dirtyimage'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(null=True, to='manager.blogtag'),
        ),
    ]
