# Generated by Django 4.2.3 on 2023-07-17 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_blog_images_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirtyimage',
            name='parent_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.blog'),
        ),
    ]
