# Generated by Django 4.2.3 on 2023-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_feed_alter_blog_options_alter_blogtag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
