# Generated by Django 4.2.4 on 2023-08-08 03:46

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=manager.models.new_uid, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(default=dict)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.blog')),
            ],
            options={
                'verbose_name': 'Scrape Log',
                'verbose_name_plural': 'Scrapes Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
